### ISSUE TITLE
Propose enhancements

### ISSUE THREAD

**Issue by eddy147** [subhamBharadwaz/gloomy-night#4]
Hi, great color theme, some things would be nice to be improved tough:

- the selected file in the project bar on the left is not really visibile. I would suggest something like 
` {
            "list.activeSelectionBackground": "#234",
            "list.inactiveSelectionBackground": "#234"
 },`

#234 I just used to make it more visible, I am sure you have better ideas.

- comments, for me, are too bright and distract from the main code. I'd rather see something like
`  {
            "comments": "#9AA"
    }`
    
  Although from your preview picture your comments are OK, maybe it's just in mine because I use elixir as language.
    
   Thx in advance

**Comment by subhamBharadwaz** [comment]
Hey sorry for late reply! Thank you for bringing these issues to my attention. Your input is invaluable in enhancing the theme and making it more usable for everyone. I'll incorporate your suggestions into the theme and release an updated version soon. If you want to make the changes by yourself please do it!🍻

Once again, thank you for taking the time to provide feedback and for your kind words. Your contribution is greatly appreciated!
